# Generated by Django 5.1.6 on 2025-02-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=500)),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
