# Generated by Django 5.1.6 on 2025-02-19 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovueApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableGenre',
            fields=[
                ('genreid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TableMovie',
            fields=[
                ('movieid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('releasedate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genreid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovueApp.tablegenre')),
                ('movieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovueApp.tablemovie')),
            ],
        ),
    ]
