# Generated by Django 5.1.6 on 2025-02-19 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovueApp', '0002_tablegenre_tablemovie_moviegenre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewid', models.AutoField(primary_key=True, serialize=False)),
                ('reviewtext', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField()),
                ('ratingscore', models.IntegerField(max_length=10)),
                ('genreid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovueApp.tablegenre')),
                ('movieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovueApp.tablemovie')),
            ],
        ),
    ]
