# Generated by Django 5.1.6 on 2025-02-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovueApp', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ratingscore',
            field=models.IntegerField(),
        ),
    ]
