# Generated by Django 5.1.6 on 2025-02-19 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovueApp', '0004_alter_review_ratingscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ratingscore',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('reactionid', models.AutoField(primary_key=True, serialize=False)),
                ('reactiontype', models.TextField()),
                ('reviewid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovueApp.review')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovueApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Watchtable',
            fields=[
                ('watchid', models.AutoField(primary_key=True, serialize=False)),
                ('addeddate', models.DateTimeField()),
                ('movieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovueApp.tablemovie')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovueApp.user')),
            ],
        ),
    ]
