# Generated by Django 5.1.6 on 2025-02-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovueApp', '0006_alter_reaction_userid_alter_watchtable_userid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TableGenre',
            new_name='Genre',
        ),
        migrations.RenameModel(
            old_name='TableMovie',
            new_name='Movie',
        ),
    ]
