# Generated by Django 5.1.6 on 2025-02-20 05:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovueApp', '0007_rename_tablegenre_genre_rename_tablemovie_movie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='genreid',
        ),
        migrations.RemoveField(
            model_name='review',
            name='movieid',
        ),
        migrations.AddField(
            model_name='genre',
            name='movies',
            field=models.ManyToManyField(through='MovueApp.MovieGenre', to='MovueApp.movie'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reactiontype',
            field=models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('funny', 'Funny'), ('sad', 'Sad')], max_length=10),
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('reviewid', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('review', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField()),
                ('movieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovueApp.movie')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reviewid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovueApp.reviewrating'),
        ),
        migrations.DeleteModel(
            name='Watchtable',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
