# Generated by Django 5.1.6 on 2025-02-20 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovueApp', '0008_remove_review_genreid_remove_review_movieid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('watchlistid', models.AutoField(primary_key=True, serialize=False)),
                ('added_date', models.DateTimeField()),
                ('movieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovueApp.movie')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
