# Generated by Django 5.1.6 on 2025-02-20 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovueApp', '0009_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='movies',
        ),
        migrations.DeleteModel(
            name='MovieGenre',
        ),
    ]
