# Generated by Django 5.1.6 on 2025-02-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovueApp', '0010_remove_genre_movies_delete_moviegenre'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='movies',
            field=models.ManyToManyField(related_name='movies', to='MovueApp.movie'),
        ),
    ]
