# Generated by Django 5.1.6 on 2025-02-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovueApp', '0012_remove_genre_movies_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
