# Generated by Django 5.1.6 on 2025-02-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovueApp', '0013_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='MovueApp/static/posters/'),
        ),
    ]
