# Generated by Django 5.1.6 on 2025-02-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovueApp', '0013_alter_reviewrating_timestamp'),
        ('MovueApp', '0014_alter_movie_poster'),
    ]

    operations = [
    ]
