# Generated by Django 5.1.6 on 2025-02-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovueApp', '0015_merge_20250225_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='poster/'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
