# Generated by Django 5.1.6 on 2025-04-13 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovueApp', '0017_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reactiontype',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('userid', 'reviewid')},
        ),
    ]
